# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go mod download

builds:
- id: ghdl
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w
  goos:
  - linux
  - windows
  goarch:
  - amd64
- id: ghdl-macos
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w
  goos:
  - darwin
  goarch:
  - amd64
  hooks:
    post: gon .gon.hcl

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
