name: build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: SetUp
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.14.x

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/bin
          ~/go/pkg
          ~/go/src
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Dependencies
      run: GO111MODULE=off go get github.com/mfridman/tparse

    - name: Test
      run: go test -coverprofile coverage.txt -covermode atomic ./pkg/... -json | tparse -all -top

    # - name: Coverage
    #   uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     file: ./coverage.txt
    #     flags: tests
    #     name: ${{ GITHUB_REF }}-tests
